#!/bin/sh

cachedir="${XDG_CACHE_HOME:-"$HOME/.cache"}"
cache="$cachedir/dmenu_run"

[ ! -e "$cachedir" ] && mkdir -p "$cachedir"

dir=~/dev/suckless/dmenu/latest

IFS=:
if $dir/stest -dqr -n "$cache" $PATH; then
	$dir/stest -flx $PATH | sort -u | tee "$cache"
else
	cat "$cache"
fi
